#!/bin/sh

# change network settings in /env/network/eth0
# change mtd partition settings and automountpoints in /env/init/*

# user (used for network filenames)
global.user=none

# timeout in seconds before the default boot entry is started
global.autoboot_timeout=3

# default boot entry (one of /env/boot/*)
global.boot.default=sd
global.linux.bootargs.base="console=ttyO0,115200"
