#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "kernel & rootfs on SD card"
	exit
fi

global.bootm.image=/boot/uImage
#global.bootm.oftree=<path to oftree>
#global.bootm.initrd=<path to initrd>

#bootargs-root-nfs -n "<path on server>" -s <serverip>
#bootargs-root-jffs2 -m <mtdname>
#bootargs-root-ubi -r <volume> -m <mtdname>

global.linux.bootargs.root="root=/dev/mmcblk0p2 rootfstype=ext4 rootwait rw"
